### ISSUE TITLE
Can't compile with Ruby 2.4.0

### ISSUE THREAD

**Issue by parkr** [brianmario/yajl-ruby#170]
Hey @brianmario! I was just trying to install one of Jekyll's dependencies, `pygments.rb`, which depends on this gem. Unfortunately, it still uses `Fixnum`:

```text
    current directory: /Users/parkr/jekyll/jekyll/vendor/ruby/2.4.0/gems/yajl-ruby-1.2.1/ext/yajl
/Users/parkr/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20170130-68511-1xe6w28.rb extconf.rb
creating Makefile

current directory: /Users/parkr/jekyll/jekyll/vendor/ruby/2.4.0/gems/yajl-ruby-1.2.1/ext/yajl
make "DESTDIR=" clean

current directory: /Users/parkr/jekyll/jekyll/vendor/ruby/2.4.0/gems/yajl-ruby-1.2.1/ext/yajl
make "DESTDIR="
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_ext.c
yajl_ext.c:881:22: error: use of undeclared identifier 'rb_cFixnum'
    rb_define_method(rb_cFixnum, "to_json", rb_yajl_json_ext_fixnum_to_json, -1);
                     ^
1 error generated.
make: *** [yajl_ext.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/parkr/jekyll/jekyll/vendor/ruby/2.4.0/gems/yajl-ruby-1.2.1 for inspection.
Results logged to /Users/parkr/jekyll/jekyll/vendor/ruby/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/yajl-ruby-1.2.1/gem_make.out

An error occurred while installing yajl-ruby (1.2.1), and Bundler cannot continue.
Make sure that `gem install yajl-ruby -v '1.2.1'` succeeds before bundling.
```

Is this something you're interested in seeing fixed?

**Comment by brianmario** [comment]
yajl-ruby 1.3.0 added support for ruby 2.4.0 - let me know if you have any issues!
